### ISSUE TITLE
Google API keys

### ISSUE THREAD

**Issue by Stukongeluk** [rogerbosman/IKPMD#1]
Wat vinden jullie van het feit dat jullie API keys nu blootgesteld staan? Want ik zit te twijfelen of ik dat ook online moet zetten op public voor IKPMD want uh tja... abuse enz van anderen?

Maar ik hoop dat de examinatoren snel nakijken zodat je dit snel op private weer kan zetten ;D

**Comment by Stukongeluk** [comment]
Rip

**Comment by rogerbosman** [comment]
Lol
